name: Deploy to EC2 with Apache

on:
  push:
    branches:
      - main   # o la rama que uses

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout código
        uses: actions/checkout@v3   # 👈 descarga tu repo

      - name: Copiar archivos al servidor Apache
        run: |
          sudo rm -rf /var/www/html/*
          sudo cp -r * /var/www/html/
          sudo systemctl restart apache2
