name: Deploy to EC2 with Apache (both)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    strategy:
      matrix:
        runner_label: [ "web1", "web2" ]
      fail-fast: false

    runs-on:
      - self-hosted
      - ${{ matrix.runner_label }}

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Copiar archivos al servidor Apache
        run: |
          sudo rm -rf /var/www/html/*
          sudo cp -r * /var/www/html/
          sudo systemctl restart apache2
